# Generated by Django 4.1.4 on 2023-07-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sppbackend', '0002_place_description1_place_description2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
