# Generated by Django 4.1.4 on 2023-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppbackend', '0003_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description2',
        ),
        migrations.AddField(
            model_name='place',
            name='coordinates',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='place',
            name='site',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
